### PR TITLE
Add capability to execute JS code in browser context before taking screenshot.

### PR DESCRIPTION
**Pull request by fchristl**
Added a parameter (evaluate-function) to execute JavaScript code in the browser's context prior to taking a screenshot.

This is especially useful when you work with dynamic JS-based apps where you need to perform UI actions in the browser before you the state that you want to take a screenshot of.

### CODE REVIEW

**Comment by gojko** [comment]
Hi,

thanks for this, looks very interesting. generally, I'd push things like this into the fixture, I'm fine if the fixture passes that on to the screenshot engine as you've done it. Is there a reason why you'd put it in markdown instead of the fixture?

**Comment by fchristl** [comment]
Thanks for the quick reply! I wanted to limit the changes required to a minimum. If i put it in the fixture, I imagine we'd have to modify the data structure a fixture has. For example, an URL-emitting fixture like that:

    'use strict';
       module.exports = function (params) {
	   return `https://github.com/${params.name}`;
    };

would require a change of the return type to hold the additional `evaluate-function` information. E.g.

     
    'use strict';
       module.exports = function (params) {
	   return {
                url: `https://github.com/${params.name}`,
                evaluate-function: "document.getElementById('button').click();"
           };
    };

If that's acceptable to you, I'd be happy to change the implementation accordingly.

**Comment by gojko** [comment]
I prefer to write code in a level where linting is at least possible, and unit tests are an option, so I'd definitely go for a fixture in this case. we could even make it something like

```
evaluateFunction = function (document) {
document.getElementById('button').click();
}
```

in that case, it would be possible to properly test complex fixtures

**Comment by fchristl** [comment]
Thanks. I'll sit down in the next couple of days and change the implementation accordingly

**Comment by gojko** [comment]
btw, on a related note, it would be good to plan for async work immediately, as the interface to the browser is generally async. so maybe the hook should be something like `fixture.beforeScreenshot = function (document)` expecting back either a Promise or a sync return value.

**Comment by gojko** [comment]
Hi,

I published this on NPM as 0.2.0 now. thanks

**Comment by fchristl** [comment]
Thanks!

**Pull request merged**
